---
- name: Install Apache to slave server
  hosts: webservers
  become: yes
  vars:
    port: 80
    email: segunalofun@protonmail.com
    domain: 18.207.149.105
    server: www.segunalofun.me
    domain_name: laravel
  tasks:
     - name: Install Apache2 Package
       package: 
          name: apache2
          state: latest
          update_cache: yes
     - name: Start Apache2
       service: 
           name: apache2
           state: started
           
     - name: Add Firewall Rule 
       firewalld: 
            port: 80/tcp
            permanent: true
            state: enabled
     - name: Restart firewalld
       service: 
            name: firewalld 
            state: restarted
     - name: Copy laravel.conf into apache dir
       template: 
             src: /home/banzy/laravel.conf
             dest: /etc/apache2/sites-available/
     - name: a2enmod laravel.conf
       command: a2enmod rewrite
     - name: a2ensite laravel.conf
       command: a2ensite "{{domain_name}}".conf
     - name: restart apache2
       service: 
            name: apache2 
            state: restarted
        
