---
- name: Securing mysql installation on the client node
  hosts: webservers
  become: yes
  vars:
    RootPasswd: Banzy2022
  tasks:
     - name: Removes all anonymous user accounts
       mysql_user:
         name: ''
         host_all: yes
         state: absent
         login_user: root
         login_password: "{{RootPasswd}}"
     - name: Remove the test database and access it
       mysql_db:
         name: test
         state: absent
         login_user: root
         login_password: "{{RootPasswd}}"
