---
- name: Install laravel and it's dependencies to the client node
  hosts: webservers
  become: yes
  vars:
    HostName: laravel
  tasks:
     - name: Install the following packages to the client node
       ansible.builtin.package:
          name:
            - curl
            - wget
            - git
            - unzip
            - php8.1-mysql
            - php-curl
            - php-xml
          update_cache: yes
          state: latest
     #- name: Adding git Username and email
       #shell: |
         #sudo git config --global user.name Banzyworld
         #sudo git config --global user.email segunalofun@protonmail.com
     - name: Download composer installer
       ansible.builtin.get_url:
           url: https://getcomposer.org/installer
           dest: /usr/src/
     - name: Download and install composer
       shell: curl -sS https://getcomposer.org/installer | php
       args:
         chdir: /usr/src/
         creates: /usr/local/bin/composer
         warn: false
     - name: Add composer to global path
       copy:
         dest: /usr/local/bin/composer
         group: root
         mode: '0755'
         owner: root
         src: /usr/src/composer.phar
         remote_src: yes
     - name: Make a directory in /var/www path
       ansible.builtin.file:
          path: /var/www/{{ HostName }}
          state: directory
          mode: '0775'
     #- name: Clone laravel app to client node
       #git:
        # repo:  https://github.com/f1amy/laravel-realworld-example-app.git
         #dest:  /var/www/{{ HostName }}
     - name: Change ownership permission
       ansible.builtin.file:
         path: /var/www/{{ HostName }}
         state: directory
         recurse: yes
         owner: www-data
         group: www-data
     - name: Set permission for the user
       ansible.builtin.file:
         path: /var/www/{{ HostName }}
         state: directory
         recurse: yes
         mode: '0775'
     - name: Set permission for storage
       ansible.builtin.file:
         path: /var/www/{{ HostName }}/storage
         state: directory
         recurse: yes
         mode: '0775'
     - name: Set permission for bootstrap
       ansible.builtin.file:
         path: /var/www/{{ HostName }}/bootstrap/cache
         state: directory
         recurse: yes
         mode: '0775'
     - name: Copy env file
       copy:
         src: /home/banzy/.env
         dest: /var/www/{{ HostName }}
     - name: Remove the web.php inside routes dir
       shell: sudo rm -rf /var/www/{{HostName }}/routes/web.php
     - name: Copy web.php to routes dir
       template:
          src: /home/banzy/web.php
          dest: /var/www/{{ HostName }}/routes/
     - name: Install laravel dependencies with composer install
       become: false
       community.general.composer:
         command: install
         global_command: false
         working_dir: /var/www/laravel
     - name: Update the laravel project using composer update mod
       become: false
       community.general.composer:
         command: update
         working_dir: /var/www/{{ HostName }}/
         global_command: false
     - name: Generate the project key
       ansible.builtin.shell: |
         cd /var/www/{{ HostName }}/
         php artisan key:generate
     - name: clear the config cache
       ansible.builtin.shell: |
         cd /var/www/{{ HostName }}
         sudo php artisan config:cache
     #- name: Fresh the migration table
       #ansible.builtin.shell: |
         #cd /var/www/{{ HostName }}
         #sudo php artisan migrate:refresh
     - name: Migrate the database
       ansible.builtin.shell: |
         cd /var/www/{{ HostName }}/ artisan migrate
